### ISSUE TITLE
Usage with babel/es2015/2016...?

### ISSUE THREAD

**Issue by mrtnbroder** [plaid/transcribe#12]
Is it possible to use this with es6 module syntax and a 'modular' approach?

e.g. given a modular structure

```
├── Parse
│   ├── index.js
│   ├── parseDate.js
│   ├── parseFloat.js
│   ├── parseInt.js
│   └── parseJson.js
├── RegExp
│   ├── index.js
│   ├── match.js
│   ├── regex.js
│   ├── regexEscape.js
│   └── test.js
```

and each function has a doc-note, how could I make this work together with transcribe?

**Comment by davidchambers** [comment]
Transcribe knows nothing about any particular language or module format (which I appreciate).

You would need to provide all the file paths in the order in which you want the transcriptions to be concatenated:

```shell
node_modules/.bin/transcribe --url '...' -- {Parse/{index,parseDate,parseFloat,parseInt,parseJson},RegExp/{index,match,regex,regexEscape,test}}.js
```

Maintaining a list of file paths may be a drag. The nice thing about having everything in one big (source) file is that it maps neatly to the standard approach to documenting projects on GitHub: one big (readme) file. If instead one has 100 source files, a more natural approach to documenting these might involve 100 HTML files with an interface for finding the ones of interest. This is out of scope for Transcribe, though it's something that could be built on top of Transcribe.

I imagine sanctuary-js/sanctuary#261 provided the motivation for this issue. I suggest hard-coding a list of file paths until we think of a better approach.

**Comment by mrtnbroder** [comment]
Indeed, sanctuary provided the motivation ;)

From what I can see, it's not possible to provide a local file as the source to transcribe, is that correct? That would be a great feature addition.

And Welcome to Berlin! ;)

**Comment by mrtnbroder** [comment]
nvm.. it actualls __does__ read a local file. dumb me. It looked like, by providing the `url` part, that it reads from a remote source.

Thanks!

**Comment by mrtnbroder** [comment]
Closing the issue since I now have my answer :)

**Comment by davidchambers** [comment]
> nvm.. it actuall[y] __does__ read a local file. dumb me. It looked like, by providing the `url` part, that it reads from a remote source.

I see how this can be confusing. The `--url` argument is for specifying where the source code lives so that each heading can link to the appropriate line in the source code. :)
