### ISSUE TITLE
Add an option to insert generated text into a specific place in the README

### ISSUE THREAD

**Issue by albrow** [plaid/transcribe#9]
Currently, Transcribe prints results to stdout. I imagine the most common use case is to then write the output to a file using the `>` or `>>` bash operators.

It would be nice if Transcribe accepted an option to insert the generated text into a specific place in the README. The use case is for docs which contain a large amount of explanatory text, and maybe even diagrams, tables, graphs, etc. It is inconvenient to have to put all of this in comments in the source code.

For example, the [markdown-toc package](https://github.com/jonschlinkert/markdown-toc) uses special comments `<!-- toc -->` and `<!-- tocstop -->` to indicate where the table of contents should be inserted in the README.

Example README:

```markdown
# My Lib

## Introduction

A paragraph of text about what my lib is and what it can be used for.

| maybe   | there    | are   |
|---------|----------|-------|
| tables  | and      | other |
| graphic | elements | here  |

## Installation

Instructions for how to install my lib.

## API Documentation

<!-- transcribe start -->
<!-- transcribe stop -->
```

**Comment by davidchambers** [comment]
This would be a very useful feature. I don't yet have a clear idea of the API changes involved. I imagine we'd support __`--output`__. Would this be used *only* when one wishes to insert content into an existing file, or could `--output README.md` be used in place of `>README.md` in all cases?
